#!/usr/bin/env bash
set -ex

source /opt/conda/etc/profile.d/conda.sh
conda activate z1_statistics

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u run_capsule.py "$@"
